name: up_afv
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  intl: ^0.17.0
  connectivity: ^3.0.6
  google_fonts: ^2.1.0
  sqflite:
  path_provider: ^2.0.9
  flip_card: ^0.6.0
  font_awesome_flutter: ^9.2.0
  url_launcher:
  device_info_plus: ^3.2.2
  geolocator:
  dio: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.1
  flutter_lints: ^1.0.4
  flutter_native_splash: ^2.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/

